import java.sql.*;
import dbmsproject.Connectionprovider;
import java.awt.Insets;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class addnewdonarpage extends javax.swing.JFrame {

    /**
     * Creates new form addnewdonarpage
     */
    public addnewdonarpage() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int x_size=(int)tk.getScreenSize().getWidth();
        int y_size=(int)tk.getScreenSize().getHeight();
        Insets scnMax=Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize=scnMax.bottom;
        this.setSize(x_size,y_size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        gendercombo = new javax.swing.JComboBox<>();
        mblnotxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bldgrpcombo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        savebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        citytxt = new javax.swing.JTextArea();
        idlbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Add New Donor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 470, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 1365, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Donor ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Of Birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        nametxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 290, 45));

        emailtxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        getContentPane().add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 290, 45));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, -1, -1));

        gendercombo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        gendercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        getContentPane().add(gendercombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 120, 250, 45));

        mblnotxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        getContentPane().add(mblnotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 290, 45));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Blood Group");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("City");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 223, -1));

        bldgrpcombo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bldgrpcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "O+", "B+", "AB+", "A-", "O-", "B-", "AB-" }));
        getContentPane().add(bldgrpcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, 250, 45));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 602, 1365, 0));

        savebtn.setBackground(new java.awt.Color(255, 255, 255));
        savebtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 51, 51));
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, -1, -1));

        resetbtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(255, 51, 51));
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, -1, -1));

        closebtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        closebtn.setForeground(new java.awt.Color(255, 51, 51));
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 620, -1, -1));

        jDateChooser1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 306, 290, 50));

        citytxt.setColumns(20);
        citytxt.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        citytxt.setRows(5);
        jScrollPane1.setViewportView(citytxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, 250, 180));

        idlbl.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        idlbl.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(idlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 290, 40));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1670, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try
        {
            Connection conn=Connectionprovider.getCon();
            Statement st1=conn.createStatement();
            ResultSet rs1=st1.executeQuery("select max(Donar_id) from donar");
            if(rs1.first())
            {
                int dnr_id=rs1.getInt(1);
                dnr_id=dnr_id+1;
                String s1=String.valueOf(dnr_id);
                idlbl.setText(s1);
            }
            else
            {
                idlbl.setText("1");
            }   
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formComponentShown

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closebtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new addnewdonarpage().setVisible(true);
    }//GEN-LAST:event_resetbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        String Donar_id=idlbl.getText();
        String Donar_name=nametxt.getText();
        SimpleDateFormat date_format=new SimpleDateFormat("dd-MM-YYYY");
        String DonarDOB=date_format.format(jDateChooser1.getDate());
        String Donar_email=emailtxt.getText();
        String Donar_mobileno=mblnotxt.getText();
        String Donar_gender=(String)gendercombo.getSelectedItem();
        String Donar_Bloodgrp=(String)bldgrpcombo.getSelectedItem();
        String Donar_city=citytxt.getText();
        
        try
        {
          Connection conn=Connectionprovider.getCon();
          Statement st2=conn.createStatement();
          st2.executeUpdate("insert into Donar values('"+Donar_id+"','"+Donar_name+"','"+DonarDOB+"','"+Donar_email+"','"+Donar_mobileno+"','"+Donar_gender+"','"+Donar_Bloodgrp+"','"+Donar_city+"')");
          JOptionPane.showMessageDialog(null,"Successfully Updated");
          setVisible(false);
          new addnewdonarpage().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_savebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addnewdonarpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addnewdonarpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addnewdonarpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addnewdonarpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new addnewdonarpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bldgrpcombo;
    private javax.swing.JTextArea citytxt;
    private javax.swing.JButton closebtn;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JComboBox<String> gendercombo;
    private javax.swing.JLabel idlbl;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField mblnotxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables
}
