import java.sql.*;
import dbmsproject.Connectionprovider;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class Delete_Donarform extends javax.swing.JFrame {

    /**
     * Creates new form Delete_Donarform
     */
    public Delete_Donarform() {
       initComponents();
       Toolkit tk=Toolkit.getDefaultToolkit();
       int x_size=(int)tk.getScreenSize().getWidth();
       int y_size=(int)tk.getScreenSize().getHeight();
       Insets scnMax=Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
       int taskBarSize=scnMax.bottom;
       this.setSize(x_size,y_size);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        delete_dnridtxt = new javax.swing.JTextField();
        usearchdonarbtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        delete_nametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        delete_dobtxt = new javax.swing.JTextField();
        delete_emailidtxt = new javax.swing.JTextField();
        delete_mbltxt = new javax.swing.JTextField();
        delete_gndrtxt = new javax.swing.JTextField();
        delete_bldgrptxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        delete_citytxt = new javax.swing.JTextArea();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        resetbtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1208, 690));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Donor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 25, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 100, 1163, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Donor ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        delete_dnridtxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delete_dnridtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_dnridtxtActionPerformed(evt);
            }
        });
        getContentPane().add(delete_dnridtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 142, 57));

        usearchdonarbtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        usearchdonarbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\icons8-search-48.png")); // NOI18N
        usearchdonarbtn.setText("Search");
        usearchdonarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usearchdonarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(usearchdonarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 230, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 202, 1160, 0));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        delete_nametxt.setBackground(new java.awt.Color(204, 204, 204));
        delete_nametxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        delete_nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_nametxtActionPerformed(evt);
            }
        });
        getContentPane().add(delete_nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 290, 56));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel4.setText("Date Of Birth");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel5.setText("Email ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel6.setText("Mobile number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel8.setText("Blood Group");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel9.setText("City");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, -1, -1));

        delete_dobtxt.setBackground(new java.awt.Color(204, 204, 204));
        delete_dobtxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        delete_dobtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_dobtxtActionPerformed(evt);
            }
        });
        getContentPane().add(delete_dobtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 290, 55));

        delete_emailidtxt.setBackground(new java.awt.Color(204, 204, 204));
        delete_emailidtxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        delete_emailidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_emailidtxtActionPerformed(evt);
            }
        });
        getContentPane().add(delete_emailidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 290, 54));

        delete_mbltxt.setBackground(new java.awt.Color(204, 204, 204));
        delete_mbltxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        getContentPane().add(delete_mbltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 290, 55));

        delete_gndrtxt.setBackground(new java.awt.Color(204, 204, 204));
        delete_gndrtxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        getContentPane().add(delete_gndrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 250, 213, 56));

        delete_bldgrptxt.setBackground(new java.awt.Color(204, 204, 204));
        delete_bldgrptxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        getContentPane().add(delete_bldgrptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, 213, 54));

        delete_citytxt.setBackground(new java.awt.Color(204, 204, 204));
        delete_citytxt.setColumns(20);
        delete_citytxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        delete_citytxt.setRows(5);
        jScrollPane1.setViewportView(delete_citytxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 213, 120));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 672, -1, 20));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 614, 1160, -1));

        resetbtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 640, -1, -1));

        closebtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, -1, -1));

        deletebtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, -1, 50));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 202, 1150, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usearchdonarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usearchdonarbtnActionPerformed
        // TODO add your handling code here:
        String Donar_id=delete_dnridtxt.getText();
        try
        {
            Connection conn=Connectionprovider.getCon();
            Statement st1=conn.createStatement();
            ResultSet rs1=st1.executeQuery("select * from Donar where Donar_id='"+Donar_id+"'");
            if(rs1.next())
            {
                delete_nametxt.setText(rs1.getString(2));
                delete_dobtxt.setText(rs1.getString(3));
                delete_emailidtxt.setText(rs1.getString(4));
                delete_mbltxt.setText(rs1.getString(5));
                delete_gndrtxt.setText(rs1.getString(6));
                delete_bldgrptxt.setText(rs1.getString(7));
                delete_citytxt.setText(rs1.getString(8));
                delete_dnridtxt.setEditable(false);
            }
            else
            JOptionPane.showMessageDialog(null,"The Donar id you have entered does not Exist.");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_usearchdonarbtnActionPerformed

    private void delete_dnridtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_dnridtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_dnridtxtActionPerformed

    private void delete_dobtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_dobtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_dobtxtActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        String Donar_id=delete_dnridtxt.getText();
        try
        {
            Connection conn=Connectionprovider.getCon();
            Statement st1=conn.createStatement();
            st1.executeUpdate("Delete from Donar where Donar_id='"+Donar_id+"'");
            JOptionPane.showMessageDialog(null,"Successfully Deleted.");
            setVisible(false);
            new  Delete_Donarform().setVisible(true);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Delete_Donarform().setVisible(true);
    }//GEN-LAST:event_resetbtnActionPerformed

    private void delete_emailidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_emailidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_emailidtxtActionPerformed

    private void delete_nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_nametxtActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
          setVisible(false);
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Donarform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Donarform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Donarform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Donarform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Donarform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JTextField delete_bldgrptxt;
    private javax.swing.JTextArea delete_citytxt;
    private javax.swing.JTextField delete_dnridtxt;
    private javax.swing.JTextField delete_dobtxt;
    private javax.swing.JTextField delete_emailidtxt;
    private javax.swing.JTextField delete_gndrtxt;
    private javax.swing.JTextField delete_mbltxt;
    private javax.swing.JTextField delete_nametxt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton usearchdonarbtn;
    // End of variables declaration//GEN-END:variables
}
