import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class home_page extends javax.swing.JFrame {

    /**
     * Creates new form home_page
     */
    public home_page() {
        initComponents();
         Toolkit tk=Toolkit.getDefaultToolkit();
        int x_size=(int)tk.getScreenSize().getWidth();
        int y_size=(int)tk.getScreenSize().getHeight();
        Insets scnMax=Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize=scnMax.bottom;
        this.setSize(x_size,y_size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        addnewoptn = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        updtoptn = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        viewoptn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        srchbylocnoptn = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        srchbybldgrp = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        deleteoptn = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        increaseoptn = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        decreaseoptn = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        detailsoptn = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        logoutoptn = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        exitoptn = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();

        jMenuItem1.setText("jMenuItem1");

        jMenu7.setText("jMenu7");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\OneDrive\\Pictures\\bloodbackgroundresized.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\external-donor-human-body-anatomy-good-lines-kalash-2.png")); // NOI18N
        jMenu1.setText("Donor");
        jMenu1.add(jSeparator1);

        addnewoptn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        addnewoptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\add (1).png")); // NOI18N
        addnewoptn.setText("Add new donor");
        addnewoptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewoptnActionPerformed(evt);
            }
        });
        jMenu1.add(addnewoptn);
        jMenu1.add(jSeparator2);

        updtoptn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        updtoptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\approve-and-update.png")); // NOI18N
        updtoptn.setText("Update donor");
        updtoptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtoptnActionPerformed(evt);
            }
        });
        jMenu1.add(updtoptn);
        jMenu1.add(jSeparator3);

        viewoptn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        viewoptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\view.png")); // NOI18N
        viewoptn.setText("View all donors");
        viewoptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewoptnActionPerformed(evt);
            }
        });
        jMenu1.add(viewoptn);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\search-client.png")); // NOI18N
        jMenu2.setText("Search Donor");
        jMenu2.add(jSeparator4);

        srchbylocnoptn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        srchbylocnoptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\search-location.png")); // NOI18N
        srchbylocnoptn.setText("Search by location");
        srchbylocnoptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchbylocnoptnActionPerformed(evt);
            }
        });
        jMenu2.add(srchbylocnoptn);
        jMenu2.add(jSeparator5);

        srchbybldgrp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        srchbybldgrp.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\external-blood-drop-healthcare-tanah-basah-basic-outline-tanah-basah.png")); // NOI18N
        srchbybldgrp.setText("Search by blood group");
        srchbybldgrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchbybldgrpActionPerformed(evt);
            }
        });
        jMenu2.add(srchbybldgrp);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\external-delete-user-user-interface-aficons-studio-glyph-aficons-studio.png")); // NOI18N
        jMenu3.setText("Delete donor");
        jMenu3.add(jSeparator6);

        deleteoptn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        deleteoptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\delete-forever.png")); // NOI18N
        deleteoptn.setText("Delete donor");
        deleteoptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteoptnActionPerformed(evt);
            }
        });
        jMenu3.add(deleteoptn);
        jMenu3.add(jSeparator10);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\secured-delivery.png")); // NOI18N
        jMenu4.setText("Stock");
        jMenu4.add(jSeparator7);

        increaseoptn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        increaseoptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\bullish.png")); // NOI18N
        increaseoptn.setText("Increase");
        increaseoptn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        increaseoptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseoptnActionPerformed(evt);
            }
        });
        jMenu4.add(increaseoptn);
        jMenu4.add(jSeparator8);

        decreaseoptn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        decreaseoptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\bearish.png")); // NOI18N
        decreaseoptn.setText("Decrease");
        decreaseoptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseoptnActionPerformed(evt);
            }
        });
        jMenu4.add(decreaseoptn);
        jMenu4.add(jSeparator9);

        detailsoptn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        detailsoptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\details.png")); // NOI18N
        detailsoptn.setText("Details");
        detailsoptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsoptnActionPerformed(evt);
            }
        });
        jMenu4.add(detailsoptn);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\close-window.png")); // NOI18N
        jMenu6.setText("Exit");
        jMenu6.add(jSeparator13);

        logoutoptn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        logoutoptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\icons8-logout-24.png")); // NOI18N
        logoutoptn.setText("Logout");
        logoutoptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutoptnActionPerformed(evt);
            }
        });
        jMenu6.add(logoutoptn);
        jMenu6.add(jSeparator11);

        exitoptn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        exitoptn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\close-window.png")); // NOI18N
        exitoptn.setText("Exit application");
        exitoptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitoptnActionPerformed(evt);
            }
        });
        jMenu6.add(exitoptn);
        jMenu6.add(jSeparator15);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addnewoptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewoptnActionPerformed
        // TODO add your handling code here:
        new addnewdonarpage().setVisible(true);
    }//GEN-LAST:event_addnewoptnActionPerformed

    private void srchbybldgrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchbybldgrpActionPerformed
        // TODO add your handling code here:
        new SearchDonars_onbldgrp().setVisible(true);
    }//GEN-LAST:event_srchbybldgrpActionPerformed

    private void logoutoptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutoptnActionPerformed
        // TODO add your handling code here:
        int y=JOptionPane.showConfirmDialog(null,"Do you want to logout","Select",JOptionPane.YES_NO_OPTION);
        if(y==0)
        {
            setVisible(false);
            new loginform().setVisible(true);
        }
    }//GEN-LAST:event_logoutoptnActionPerformed

    private void exitoptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitoptnActionPerformed
        // TODO add your handling code here:
         int z=JOptionPane.showConfirmDialog(null,"Do you want to exit application","Select",JOptionPane.YES_NO_OPTION);
        if(z==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitoptnActionPerformed

    private void updtoptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtoptnActionPerformed
        // TODO add your handling code here:
        new updateDonar_form().setVisible(true);
    }//GEN-LAST:event_updtoptnActionPerformed

    private void viewoptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewoptnActionPerformed
        // TODO add your handling code here:
        new viewalldnrs_form().setVisible(true);
    }//GEN-LAST:event_viewoptnActionPerformed

    private void srchbylocnoptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchbylocnoptnActionPerformed
        // TODO add your handling code here:
        new SearchDonars_onlocn().setVisible(true);
    }//GEN-LAST:event_srchbylocnoptnActionPerformed

    private void increaseoptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseoptnActionPerformed
        // TODO add your handling code here:
        new stock_increase().setVisible(true);
    }//GEN-LAST:event_increaseoptnActionPerformed

    private void decreaseoptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseoptnActionPerformed
        // TODO add your handling code here:
        new stock_decrease().setVisible(true);
    }//GEN-LAST:event_decreaseoptnActionPerformed

    private void detailsoptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsoptnActionPerformed
        // TODO add your handling code here:
        new totalstock_details().setVisible(true);
    }//GEN-LAST:event_detailsoptnActionPerformed

    private void deleteoptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteoptnActionPerformed
        // TODO add your handling code here:
        new Delete_Donarform().setVisible(true);
    }//GEN-LAST:event_deleteoptnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addnewoptn;
    private javax.swing.JMenuItem decreaseoptn;
    private javax.swing.JMenuItem deleteoptn;
    private javax.swing.JMenuItem detailsoptn;
    private javax.swing.JMenuItem exitoptn;
    private javax.swing.JMenuItem increaseoptn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem logoutoptn;
    private javax.swing.JMenuItem srchbybldgrp;
    private javax.swing.JMenuItem srchbylocnoptn;
    private javax.swing.JMenuItem updtoptn;
    private javax.swing.JMenuItem viewoptn;
    // End of variables declaration//GEN-END:variables
}
