import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.*;
import dbmsproject.Connectionprovider;
import java.awt.Insets;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class SearchDonars_onbldgrp extends javax.swing.JFrame {

    /**
     * Creates new form SearchDonars_onbldgrp
     */
    public SearchDonars_onbldgrp() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
       int x_size=(int)tk.getScreenSize().getWidth();
       int y_size=(int)tk.getScreenSize().getHeight();
       Insets scnMax=Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
       int taskBarSize=scnMax.bottom;
       this.setSize(x_size,y_size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        bldgrptxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        srchDbldgrp_closebtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search Donor Based On Blood Group");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 89, 1140, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Blood Group");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 109, -1, -1));

        bldgrptxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bldgrptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldgrptxtActionPerformed(evt);
            }
        });
        bldgrptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bldgrptxtKeyReleased(evt);
            }
        });
        getContentPane().add(bldgrptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 109, 236, 50));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 194, 1140, -1));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 226, 1140, 334));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 597, 1140, -1));

        srchDbldgrp_closebtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        srchDbldgrp_closebtn.setText("Close");
        srchDbldgrp_closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchDbldgrp_closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(srchDbldgrp_closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 630, 143, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srchDbldgrp_closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchDbldgrp_closebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_srchDbldgrp_closebtnActionPerformed

    private void bldgrptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldgrptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldgrptxtActionPerformed

    private void bldgrptxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bldgrptxtKeyReleased
        // TODO add your handling code here:
        String Donar_Bloodgrp=bldgrptxt.getText();
        try
        {
            Connection conn=Connectionprovider.getCon();
            Statement st1=conn.createStatement();
            ResultSet rs1=st1.executeQuery("select * from Donar where Donar_Bloodgrp like '%"+Donar_Bloodgrp+"%'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_bldgrptxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchDonars_onbldgrp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchDonars_onbldgrp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchDonars_onbldgrp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDonars_onbldgrp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchDonars_onbldgrp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bldgrptxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton srchDbldgrp_closebtn;
    // End of variables declaration//GEN-END:variables
}
