import java.sql.*;
import dbmsproject.Connectionprovider;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class updateDonar_form extends javax.swing.JFrame {

    /**
     * Creates new form updateDonar_form
     */
    public updateDonar_form() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int x_size=(int)tk.getScreenSize().getWidth();
        int y_size=(int)tk.getScreenSize().getHeight();
        Insets scnMax=Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize=scnMax.bottom;
        this.setSize(x_size,y_size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        udonaridtxt = new javax.swing.JTextField();
        usearchdonarbtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        unametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uemailtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        umblnotxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        uupdatebtn = new javax.swing.JButton();
        uresetbtn = new javax.swing.JButton();
        uclosebtn = new javax.swing.JButton();
        ugendertxt = new javax.swing.JTextField();
        ubldgrptxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ucitytxt = new javax.swing.JTextArea();
        udobtxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1365, 673));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update New Donor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 20, 450, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 76, 1276, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Donor ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 184, 51));

        udonaridtxt.setBackground(new java.awt.Color(204, 204, 204));
        udonaridtxt.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        getContentPane().add(udonaridtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 290, 41));

        usearchdonarbtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        usearchdonarbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\icons8-search-48.png")); // NOI18N
        usearchdonarbtn.setText("Search");
        usearchdonarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usearchdonarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(usearchdonarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 230, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 170, 1280, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        unametxt.setBackground(new java.awt.Color(204, 204, 204));
        unametxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        getContentPane().add(unametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 290, 50));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Of Birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        uemailtxt.setBackground(new java.awt.Color(204, 204, 204));
        uemailtxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        getContentPane().add(uemailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 290, 45));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        umblnotxt.setBackground(new java.awt.Color(204, 204, 204));
        umblnotxt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        getContentPane().add(umblnotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 290, 45));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Blood Group");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("City");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 223, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 589, 1291, -1));

        uupdatebtn.setBackground(new java.awt.Color(153, 153, 153));
        uupdatebtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        uupdatebtn.setText("Update");
        uupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uupdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(uupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, -1, -1));

        uresetbtn.setBackground(new java.awt.Color(153, 153, 153));
        uresetbtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        uresetbtn.setText("Reset");
        uresetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uresetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(uresetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, -1, -1));

        uclosebtn.setBackground(new java.awt.Color(153, 153, 153));
        uclosebtn.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        uclosebtn.setText("Close");
        uclosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uclosebtnActionPerformed(evt);
            }
        });
        getContentPane().add(uclosebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 620, -1, -1));

        ugendertxt.setBackground(new java.awt.Color(204, 204, 204));
        ugendertxt.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        getContentPane().add(ugendertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, 250, -1));

        ubldgrptxt.setBackground(new java.awt.Color(204, 204, 204));
        ubldgrptxt.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        getContentPane().add(ubldgrptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, 250, -1));

        ucitytxt.setBackground(new java.awt.Color(204, 204, 204));
        ucitytxt.setColumns(20);
        ucitytxt.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        ucitytxt.setRows(5);
        jScrollPane1.setViewportView(ucitytxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 410, 250, 140));

        udobtxt.setBackground(new java.awt.Color(204, 204, 204));
        udobtxt.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        getContentPane().add(udobtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 290, 50));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uclosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uclosebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_uclosebtnActionPerformed

    private void uresetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uresetbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new updateDonar_form().setVisible(true);
    }//GEN-LAST:event_uresetbtnActionPerformed

    private void usearchdonarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usearchdonarbtnActionPerformed
        // TODO add your handling code here:
        String Donar_id=udonaridtxt.getText();
        try
        {
            Connection conn=Connectionprovider.getCon();
            Statement st1=conn.createStatement();
            ResultSet rs1=st1.executeQuery("select * from Donar where Donar_id='"+Donar_id+"'");
            if(rs1.next())
            {
                unametxt.setText(rs1.getString(2));
                udobtxt.setText(rs1.getString(3));
                uemailtxt.setText(rs1.getString(4));
                umblnotxt.setText(rs1.getString(5));
                ugendertxt.setText(rs1.getString(6));
                ubldgrptxt.setText(rs1.getString(7));
                ucitytxt.setText(rs1.getString(8));
                udonaridtxt.setEditable(false);
            }
            else
                JOptionPane.showMessageDialog(null,"The Donar id you have entered does not Exist.");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_usearchdonarbtnActionPerformed

    private void uupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uupdatebtnActionPerformed
        // TODO add your handling code here:
        String Donar_id=udonaridtxt.getText();
        String Donar_name=unametxt.getText();
        String DonarDOB=udobtxt.getText();
        String Donar_email=uemailtxt.getText();
        String Donar_mobileno=umblnotxt.getText();
        String Donar_gender=ugendertxt.getText();
        String Donar_Bloodgrp=ubldgrptxt.getText();
        String Donar_city=ucitytxt.getText();
        try
        {
          Connection conn=Connectionprovider.getCon();
            Statement st1=conn.createStatement();
            st1.executeUpdate("update Donar set Donar_name='"+Donar_name+"',DonarDOB='"+DonarDOB+"',Donar_email='"+Donar_email+"',Donar_mobileno='"+Donar_mobileno+"',Donar_gender='"+Donar_gender+"',Donar_Bloodgrp='"+Donar_Bloodgrp+"',Donar_city='"+Donar_city+"' where Donar_id='"+Donar_id+"'");
            JOptionPane.showConfirmDialog(null,"Successfully Updated");
            setVisible(false);
            new updateDonar_form().setVisible(true);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_uupdatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateDonar_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateDonar_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateDonar_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateDonar_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateDonar_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField ubldgrptxt;
    private javax.swing.JTextArea ucitytxt;
    private javax.swing.JButton uclosebtn;
    private javax.swing.JTextField udobtxt;
    private javax.swing.JTextField udonaridtxt;
    private javax.swing.JTextField uemailtxt;
    private javax.swing.JTextField ugendertxt;
    private javax.swing.JTextField umblnotxt;
    private javax.swing.JTextField unametxt;
    private javax.swing.JButton uresetbtn;
    private javax.swing.JButton usearchdonarbtn;
    private javax.swing.JButton uupdatebtn;
    // End of variables declaration//GEN-END:variables
}
